name: Build, Push and Deploy a Docker Image to Railway

on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Encore CLI
        run: curl -L https://encore.dev/install.sh | bash

      - name: Build Docker image
        run: /home/runner/.encore/bin/encore build --config railway-infra.config.json docker myapp

      - name: Tag Docker image
        run: docker tag myapp ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

